# Generated by Django 4.1.1 on 2023-07-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_remove_task_done_alter_task_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[(1, "High"), (2, "Medium"), (3, "Low")],
                default=3,
                max_length=10,
            ),
        ),
    ]
